language: node_js
node_js:
  - "8"

cache: yarn

# install:
#   - yarn global add lerna
#   - lerna bootstrap

script:
  - cd packages/netlify-cms-backend-fs
  - yarn build

after_success:
  - yarn semantic-release
