language: node_js
node_js:
  - "8"

cache: yarn

install:
  - yarn
#   - yarn global add lerna
#   - lerna bootstrap

script:
  - cd packages/netlify-cms-backend-fs
  - yarn build:copy
  - yarn build:lib

after_success:
  - yarn semantic-release
